---
# file:  [ansible]/raspi_config/tasks/main.yml

# - name: enable raspberry pi camera
#   become: true
#   shell: "raspi-config nonint do_camera 1"

- name: minimize raspberry pi GPU memory
  become: true
  shell: "raspi-config nonint do_memory_split 64"

# - name: enable overlay filesystem
#   become: true
#   shell: "raspi-config nonint do_overlayfs 1"