---
# file:  [ansible]/roles/rpi_disable_swap/tasks/main.yml

- name: force quit swap
  become: true
  command: swapoff -a 

- name: remove dphys-swapfile package
  become: true
  apt:
    purge: true
    state: absent
    name: dphys-swapfile

- name: remove swapfile
  become: true
  file:
    state: absent
    path: /var/swap
...